#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define CMU_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./cmu_10_regular.h",
  "./cmu_10_bold.h",
  "./cmu_10_bolditalic.h",
  "./cmu_10_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define CMU_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./cmu_12_regular.h",
  "./cmu_12_bold.h",
  "./cmu_12_bolditalic.h",
  "./cmu_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define CMU_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./cmu_14_regular.h",
  "./cmu_14_bold.h",
  "./cmu_14_bolditalic.h",
  "./cmu_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define CMU_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./cmu_16_regular.h",
  "./cmu_16_bold.h",
  "./cmu_16_bolditalic.h",
  "./cmu_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
