#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define CMU_8_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./cmu_8_regular.h",
  "./cmu_8_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define CMU_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./cmu_10_regular.h",
  "./cmu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define CMU_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./cmu_12_regular.h",
  "./cmu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"