// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define CMU_10_FONT_ID (-1234567890)
#define CMU_12_FONT_ID (-362573640)
#define CMU_14_FONT_ID (1916521753)
#define CMU_16_FONT_ID (-1847444501)
#define CMU_18_FONT_ID (624192475)
#define UI_10_FONT_ID (-823541435)
#define UI_12_FONT_ID (-126318184)
#define SMALL_FONT_ID (-874196069)
