// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define CMU_10_FONT_ID (-500642869)
#define CMU_12_FONT_ID (-362573640)
#define CMU_14_FONT_ID (1916521753)
#define CMU_8_FONT_ID (1648956322)
#define UI_10_FONT_ID (-823541435)
#define UI_12_FONT_ID (-126318184)
